### ISSUE TITLE
ingress documentation outdated

### ISSUE THREAD

**Issue by riezebosch** [canonical-web-and-design/microk8s.io#510]
## Summary

`apiVersion: networking.k8s.io/v1beta1` is deprecated: https://kubernetes.io/docs/reference/using-api/deprecation-guide/

## Process

Try to apply the listed example on a microk8s cluster.

## Current and expected result

[Describe what happened and what you expected.

## Screenshot

[If relevant, include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

Should be:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: some-service
            port: 
              number: 80
```
